function codes_SERVER() {
	#macro CODE_CONNECT 0
	#macro CODE_CONNECT_COOP 1
	#macro CODE_DISCONNECT 2
	#macro CODE_HOST_COOP 3
	#macro CODE_JOIN_COOP 4
	#macro CODE_PING 5
	
	#macro CODE_LOGIN_SUCCESS 6
	#macro CODE_LOGIN_FAIL 7
	#macro CODE_LOGIN 8
	#macro CODE_SIGNUP 9
	#macro CODE_SIGNUP_SUCCESS 10
	#macro CODE_SIGNUP_FAIL 11
	
	#macro CODE_UPLOAD 12
	#macro CODE_UPLOAD_SUCCESS 13
	#macro CODE_UPLOAD_REQUEST 14
	#macro CODE_SAVE 15
	
	#macro CODE_KEYPRESS 16
	#macro CODE_KEYRELEASE 17
	#macro CODE_MOUSE_POSITION 18
	
	#macro CODE_BASIC_ATTACK 19
	#macro CODE_DAMAGED 20
	
	#macro CODE_SKILL0 21
	#macro CODE_SKILL1 22
	#macro CODE_SKILL2 23
	#macro CODE_SKILL3 24
	
	#macro CODE_KILL 25
	#macro CODE_SLIDING_TEXT 26
	#macro CODE_SKILL_INFO 27
	
	#macro CODE_EFFECT_LASER 28
	
	#macro CODE_PLACE_OBSTACLES 29
	#macro CODE_PLACE_LIGHTS 30
	#macro CODE_PLACE_TREES 31
	#macro CODE_PLACE_LAKES 32
	
	#macro CODE_SPAWN_PLAYER 33
	#macro CODE_SPAWN_NPC 34
	
	#macro CODE_TELL_PLAYER_NAME 35
	#macro CODE_TELL_PLAYER_POSITION 36
	#macro CODE_TELL_PLAYER_HP 37
	#macro CODE_TELL_PLAYER_ENERGY 38
	#macro CODE_TELL_PLAYER_ROTATION 39
	#macro CODE_TELL_PLAYER_MANA 40
	#macro CODE_TELL_PLAYER_MAXHP 41
	#macro CODE_TELL_PLAYER_MAXMANA 42
	#macro CODE_TELL_PLAYER_MAXENERGY 43
		
	#macro CODE_TELL_NPC_POSITION 44
	#macro CODE_TELL_NPC_HP 45
	#macro CODE_TELL_NPC_ENERGY 46
	#macro CODE_TELL_NPC_ROTATION 47
	#macro CODE_TELL_NPC_MANA 48
	
	#macro CODE_LOCATION 49
	
	#macro CODE_GET_ACCOUNTINFO 50
	#macro CODE_BOX_CHANGE_ACTIVE 51
	#macro CODE_GET_INVENTORY 52
	#macro CODE_BOX_CHANGE_POSITION 53
	#macro CODE_APPEARENCE 54
	#macro CODE_GET_STATISTICS 55
	#macro CODE_GET_INVENTORY_SKILL 56
	#macro CODE_GET_ACTIVE_QUESTS 57
	#macro CODE_DELETE_QUEST 58
	#macro CODE_BUY 59
	#macro CODE_SELL 60
	#macro CODE_GET_EFFECTBOXES 61
	#macro CODE_UPGRADE_SKILL 62
	#macro CODE_CHAT 63
	#macro CODE_DROP_COIN 64
	#macro CODE_COLLECT_COIN 65
	#macro CODE_SET_SKILLBOX 66
	
	#macro CODE_DIALOGUE 67
	#macro CODE_WINDOW 68
}