function DBTables_SERVER() {	
	#region TABLE: CLIENTS
	#macro CLIENTS_SOCKETID_SERVER 0
	#macro CLIENTS_IP_SERVER 1
	#endregion
	
	#region TABLE: PLAYERS
	#macro PLAYERS_SOCKETID_SERVER 0
	#macro PLAYERS_ACCID_SERVER 1
	#macro PLAYERS_IP_SERVER 2 // Repeat
	#macro PLAYERS_LOCATION_SERVER 3
	#macro PLAYERS_HP_SERVER 4
	#macro PLAYERS_ENERGY_SERVER 5
	#macro PLAYERS_MANA_SERVER 6
	#macro PLAYERS_INSTANCE_SERVER 7
	#macro PLAYERS_X_SERVER 8
	#macro PLAYERS_Y_SERVER 9
	#macro PLAYERS_ANGLE_SERVER 10
	#macro PLAYERS_DEATHTIMER_SERVER 11
	#endregion
	
	#region TABLE: ACCOUNTS (PERMANENT)
	#macro ACCOUNTS_ACCID_SERVER 0
	#macro ACCOUNTS_PASSWORD_SERVER 1
	#macro ACCOUNTS_NICKNAME_SERVER 2
	#endregion
	
	#region TABLE: ACCOUNTINFO (PERMANENT)
	#macro ACCOUNTINFO_ACCID_SERVER 0
	#macro ACCOUNTINFO_GOLD_SERVER 1
	#macro ACCOUNTINFO_LOCATION_SERVER 2
	#macro ACCOUNTINFO_LEVEL_SERVER 3
	#macro ACCOUNTINFO_CLASS_SERVER 4
	#endregion
}